version: "3"

services:

  elasticsearch:
    image: bolingcavalry/elasticsearch-with-ik:6.5.0
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=elastic-pro
      - node.name=node_master_9200
      - node.master='True'
      - node.data='True'
      - bootstrap.memory_lock='True'
      - http.cors.enabled='True'
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  elasticsearch2:
    image: bolingcavalry/elasticsearch-with-ik:6.5.0
    container_name: elasticsearch2
    restart: always
    environment:
      - cluster.name=elastic-pro
      - node.name=node_slave_9201
      - node.master=false
      - node.data='True'
      - bootstrap.memory_lock='True'
      - http.cors.enabled='True'
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - esnet
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:6.5.0
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED='True'
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
    external_links:
      - elasticsearch

  volumes:
    esdata1:
      driver: local
    esdata2:
      driver: local

  networks:
    esnet:
